### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by mrosso10** [mrosso10/montelec-rails#30]
Los productos se agrupan en Categorías y Subcategorías, un producto puede pertenecer a una Categoría sin necesidad de subcategoría.
Paralelamente los productos tienen Fabricante

Luego en el selector de producto del wizard de stock movements pondríamos 4 selects:
- Categoría
- Subcategoría
- Fabricante
- Producto

**Comment by lsantobuono** [comment]
creo que sería raro un caso en que haya sub-sub-categorías
pero igual capaz lo mejor sería una sola tabla Category y mandarle parent_id
así estamos cubiertos por si ocurre ese caso
y que Product tenga un category_id, yo diría que obligatorio
lo malo de ese esquema es para hacer querys por categorías padre
porque los productos sólo referenciarían a las categorías de más bajo nivel
pero bueno, habría que pensarlo
Martín • 18 jun. 21:37
complicado
18 jun. 22:34
Martín Rosso (mrosso10@gmail.com)
ah, si no pongamos category_id y subcategory_id en Product
y chau
y si algún día quieren sub sub
metemos subsubcategory_id

**Comment by lsantobuono** [comment]
Falta, agregar fabricante,, nueva entidad...
filtro en productos.
fk a productos
abm normal

**Comment by lsantobuono** [comment]
En el form de movimietno de stock hay un par de quilombos la primera vez que seleccionas.
Los eventos estan todos en change pero cuando se cargan por primera vez no se disparan... supongo que habra que setear algun otro evento,
