### ISSUE TITLE
Precios

### ISSUE THREAD

**Issue by mrosso10** [mrosso10/montelec-rails#31]
Los productos tienen que tener un precio que se setea a mano. Por el momento lo haría bien simple, un atributo price en Product y chau. Lo que sí estaría bueno es que haya una pantalla copada para editar los precios sin tener que entrar a cada producto, algo con ajax tal vez.

**Comment by lsantobuono** [comment]
Agregué Precio y usé el edit on place de smart linking.
Quedo andando en el branch price_productos, aunque hay un par de cosas:

- habria que no usar en este modelo el update_and_respond, porque la gracia seria mantener elindex luego de que edite

- El edit en realidad sería de todos los campos, no solo del precio, si quisieramos hacerlo del precio habria que hacer algo mas manual supongo.

- Si les gusta el edit on place, quiza nos jodan para que lo hagamos para todos los listados, lo cual puede ser bastante paja, porque hay que agregar varios .js.erb, y un partial mas por cada modelo, y modificar formularios y giladas

**Comment by lsantobuono** [comment]
Falta, agregar fabricante,, nueva entidad...
filtro en productos.
fk a productos
abm normal

**Comment by lsantobuono** [comment]
Usar esta gema para el edit on place : https://github.com/werein/x-editable-rails

**Comment by lsantobuono** [comment]
Terminar de definir si dejamos que se editen todos los campos o solo el precio. y si dejamos formulario de edit normal o no.
