### ISSUE TITLE
Poner un piola breadcrumb

### ISSUE THREAD

**Issue by mrosso10** [mrosso10/montelec-rails#33]

**Comment by lsantobuono** [comment]
hice el piola breadcrumb, aunque no queda muy piola porque para imprimirlo en el template hay que ponerlo justo abajo de la topnavbar, y estaria mas copado quiza debajo del titulo principal de la pantalla, pero para eso habria que agregarlo a todas las pantallas, o cambiar de alguna forma el formato del layout... no se que te parece pipon

**Comment by mrosso10** [comment]
@lsantobuono 
Si, para ponerlo abajo del titulo debe haber alguna manera, con yield, content_for o algo de eso

En cuanto a electrica/metalurgica... no se, capaz en ApplicationController? la verdad no se como funca esa gema
